# Chain to existing resource server + agent config
config_paths:
- resources_servers/math_with_judge/configs/math_with_judge.yaml

# We use `_inherit_from` directives to inherit from and not use the generic config above to ensure this benchmark config is isolated.
aime25_math_with_judge_resources_server:
  _inherit_from: math_with_judge

  resources_servers:
    math_with_judge:
      datasets:
      - name: aime25
        type: benchmark
        jsonl_fpath: benchmarks/aime25/data/aime25_benchmark.jsonl
        prompt_config: benchmarks/prompts/generic/math.yaml
        prepare_script: benchmarks/aime25/prepare.py
        num_repeats: 32
        agent: aime25_math_with_judge_simple_agent
aime25_math_with_judge_simple_agent:
  _inherit_from: math_with_judge_simple_agent
  responses_api_agents:
    simple_agent:
      resources_server:
        name: aime25_math_with_judge_resources_server
