config_paths:
- resources_servers/speed_bench/configs/speed_bench.yaml

speed_bench_qualitative_resources_server:
  _inherit_from: speed_bench_resources_server

  resources_servers:
    speed_bench:
      datasets:
      - name: speed_bench_qualitative
        type: benchmark
        jsonl_fpath: benchmarks/speed-bench/data/speed_bench_qualitative_benchmark.jsonl
        prompt_config:
        prepare_script: benchmarks/speed-bench/prepare.py
        license: NVIDIA Evaluation Dataset License Agreement
        agent: speed_bench_qualitative_simple_agent
speed_bench_qualitative_simple_agent:
  _inherit_from: speed_bench_simple_agent
  responses_api_agents:
    speed_bench_agent:
      resources_server:
        name: speed_bench_qualitative_resources_server
