deepswe_resources_server:
  resources_servers:
    deepswe:
      entrypoint: app.py
      domain: coding
      verified: false

      tasks_dir: resources_servers/deepswe/data/cache/tasks
      expected_task_count: 113
      is_verifying_golden_patch: false
      task_cpu_multiplier: 2.0
      task_memory_multiplier: 2.0

      sandbox_provider: sandbox
      enforce_agent_no_network: true
      sandbox_model_server: null
      sandbox_config:
        ttl_s: 18000
        ready_timeout_s: 1200
        metadata:
          benchmark: deepswe-v1-1
          istio.io/dataplane-mode: none

      logs_dir: resources_servers/deepswe/logs
      clear_verifier_logs: true
      include_model_patch_in_response: true
