# Chain to existing agent config
config_paths:
  - responses_api_agents/tau2/configs/tau2.yaml
  - responses_api_models/openai_model/configs/OpenAI/gpt-5.2-2025-12-11.yaml

# You must fill in this key to run
gpt-5_2-2025-12-11:
  responses_api_models:
    openai_model:
      openai_api_key: ??

tau2_banking_knowledge_terminal_use_agent:
  _inherit_from: tau2_agent
  responses_api_agents:
    tau2:
      user_model_server:
        type: responses_api_models
        name: gpt-5_2-2025-12-11
      num_workers: 16
      print_step_counts: true
      datasets:
      - name: tau2_banking_knowledge_terminal_use
        type: benchmark
        jsonl_fpath: benchmarks/tau2/data/tau2_banking_knowledge_terminal_use.jsonl
        prompt_config: null
        prepare_script: benchmarks/tau2/prepare_utils/banking_terminal_use.py
        num_repeats: 8
