# Artificial Analysis Tau3-Banking configuration.
config_paths:
  - responses_api_agents/tau2/configs/tau2.yaml
  - responses_api_models/openai_model/configs/OpenAI/gpt-5.4-mini-2026-03-17.yaml

# You must fill in this key to run.
gpt-5_4-mini-2026-03-17:
  responses_api_models:
    openai_model:
      openai_api_key: ??
      extra_body:
        reasoning_effort: medium

tau2_banking_knowledge_bm25_grep_artificial_analysis_agent:
  _inherit_from: tau2_agent
  responses_api_agents:
    tau2:
      user_model_server:
        type: responses_api_models
        name: gpt-5_4-mini-2026-03-17
      max_steps: 200
      num_workers: 16
      print_step_counts: true
      datasets:
      - name: tau2_banking_knowledge_bm25_grep_artificial_analysis
        type: benchmark
        jsonl_fpath: benchmarks/tau2/data/tau2_banking_knowledge_bm25_grep.jsonl
        prompt_config: null
        prepare_script: benchmarks/tau2/prepare_utils/banking_bm25_grep.py
        num_repeats: 5
