config_paths:
- resources_servers/polymath/configs/polymath.yaml

polymath_benchmark_resources_server:
  _inherit_from: polymath
  resources_servers:
    polymath:
      should_use_judge: false

      datasets:
      - name: polymath
        type: benchmark
        jsonl_fpath: benchmarks/polymath/data/polymath_benchmark.jsonl
        prompt_config: benchmarks/prompts/generic/default.yaml
        prepare_script: benchmarks/polymath/prepare.py
        agent: polymath_benchmark_simple_agent
polymath_benchmark_simple_agent:
  _inherit_from: polymath_simple_agent
  responses_api_agents:
    simple_agent:
      resources_server:
        name: polymath_benchmark_resources_server
