# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Resources server for TIGER-Lab/SWE-Next.

SWE-Next is 2,306 rows, entirely Python, generated by the R2E ("Repo-to-Environment") pipeline:
every row ships its own prebuilt image (``docker_image``), a workdir fixed at ``/testbed``, and a
byte-identical test command across the whole dataset (see ``verification.py``) -- so there is no
per-row test-command construction, only a fixed recipe.

Verification: apply the candidate patch and the dataset's held-out ``test_patch``, run the fixed
R2E test command, and grade against ``expected_output_json`` (a whole-suite PASSED/FAILED/ERROR
snapshot from the golden-patched instance) exactly the way upstream's own
``DockerRuntime._calculate_reward_r2e`` does -- NOT a FAIL_TO_PASS/PASS_TO_PASS check, see
``verification.py``'s module docstring for why.

Set ``is_verifying_golden_patch: true`` to grade the dataset's own patch instead of an agent's,
the dataset-health check: a row whose golden patch does not resolve is a broken row.
"""

import shlex
import sys
from pathlib import Path
from time import time
from traceback import format_exc
from typing import Any

from fastapi import Request
from pydantic import BaseModel, ConfigDict

from nemo_gym.base_resources_server import (
    BaseResourcesServerConfig,
    BaseSeedSessionRequest,
    BaseSeedSessionResponse,
    BaseVerifyRequest,
    BaseVerifyResponse,
    SimpleResourcesServer,
)
from nemo_gym.global_config import get_global_config_dict
from nemo_gym.sandbox import AsyncSandbox, SandboxResources, SandboxSpec
from nemo_gym.sandbox.config import resolve_provider_config, resolve_provider_metadata
from nemo_gym.sandbox.utils import cpu_cap_env
from nemo_gym.server_utils import SESSION_ID_KEY, is_nemo_gym_fastapi_entrypoint
from resources_servers.swe_next.verification import (
    VerificationInputs,
    VerificationResult,
    drop_patch_sections,
    run_verification,
    verification_files,
)
from resources_servers.swebench.anti_cheat import apply_anti_cheat_setup


GRADING_ARTIFACTS = (
    "r2e_tests",
    "parsed_commit.json",
    "modified_files.json",
    "modified_entities.json",
    "syn_issue.json",
    "expected_test_output.json",
    "execution_result.json",
)


async def hide_grading_artifacts(sandbox: AsyncSandbox, workdir: str) -> None:
    targets = " ".join(shlex.quote(name) for name in GRADING_ARTIFACTS)
    result = await sandbox.exec(
        f"cd {shlex.quote(workdir)} && rm -rf {targets} "
        "&& if grep -qs r2e_tests run_tests.sh; then rm -f run_tests.sh; fi"
    )
    if result.return_code != 0:
        print(f"Failed to hide grading artifacts in {workdir}: {result.stdout}\n{result.stderr}", file=sys.stderr)


class SWENextResourcesServerConfig(BaseResourcesServerConfig):
    is_verifying_golden_patch: bool = False
    evaluation_timeout: int | None = 1200
    # A verdict-less run is retried on a fresh sandbox: an image pull or a flaky provider start
    # is not evidence about the patch.
    inconclusive_verification_retries: int = 1
    apply_anti_cheating: bool = True
    sandbox_provider: str
    sandbox_config: dict[str, Any]


class SWENextInstanceRequest(BaseModel):
    """One row of TIGER-Lab/SWE-Next."""

    model_config = ConfigDict(extra="allow")

    instance_id: str
    repo: str = ""
    language: str = "python"
    workdir: str = "/testbed"
    image_ref: str
    base_commit: str = ""
    patch: str = ""
    test_patch: str = ""
    problem_statement: str = ""
    # Carried for provenance only now -- grading uses expected_output_json (see verification.py).
    FAIL_TO_PASS: list[str] = []
    PASS_TO_PASS: list[str] = []
    expected_output_json: str = "{}"


class SWENextSeedSessionRequest(SWENextInstanceRequest, BaseSeedSessionRequest):
    sandbox_spec: dict[str, Any] | None = None


class SWENextSeedSessionResponse(BaseSeedSessionResponse):
    sandbox_handle: str


class SWENextVerifyRequest(SWENextInstanceRequest, BaseVerifyRequest):
    pass


class SWENextVerifyResponse(BaseVerifyResponse):
    evaluation_completed: bool
    resolved: bool
    patch_applied: bool
    instance_id: str
    language: str
    test_results: dict[str, Any] | None
    test_output: str
    error: str | None
    eval_sandbox_start_time_taken: float
    patch_verification_time_taken: float


class SWENextResourcesServer(SimpleResourcesServer):
    config: SWENextResourcesServerConfig

    def model_post_init(self, context: Any, /) -> None:
        super().model_post_init(context)
        self._session_id_to_sandbox: dict[str, AsyncSandbox] = {}
        self._session_id_to_pristine_untracked: dict[str, frozenset[str]] = {}
        self._session_id_to_base_commit: dict[str, str] = {}

    def _inputs(self, body: SWENextInstanceRequest, patch: str) -> VerificationInputs:
        return VerificationInputs(
            instance_id=body.instance_id,
            workdir=body.workdir,
            patch=patch,
            test_patch=body.test_patch,
            expected_output_json=body.expected_output_json,
        )

    async def _create_sandbox(self, body: SWENextInstanceRequest, files: dict[str, str] | None = None) -> AsyncSandbox:
        global_config_dict = get_global_config_dict()
        provider_config = resolve_provider_config(self.config.sandbox_provider, global_config_dict)
        provider_metadata = resolve_provider_metadata(self.config.sandbox_provider, global_config_dict)

        sandbox_resources = SandboxResources.from_mapping(self.config.sandbox_config.get("resources", {}))
        env = dict(self.config.sandbox_config.get("env", {}))
        if self.config.sandbox_config.get("derive_cpu_env", True):
            env = cpu_cap_env(sandbox_resources.cpu) | env

        spec = SandboxSpec(
            # The row names its own image; there is no repository template to apply.
            image=body.image_ref,
            ttl_s=self.config.sandbox_config.get("ttl_s"),
            ready_timeout_s=self.config.sandbox_config.get("ready_timeout_s"),
            # `/testbed` (`body.workdir`) is a symlink to `/workspace` that the R2E image's own
            # entrypoint normally creates on container start -- the sandbox provider never runs
            # that entrypoint, so `/testbed` does not exist yet and cannot be used as the spec's
            # workdir (every exec validates it against the live filesystem). `/workspace` is the
            # real directory the image bakes in; recreate the symlink ourselves right after start.
            workdir="/workspace",
            env=env,
            files=files or {},
            metadata=provider_metadata
            | self.config.sandbox_config.get("metadata", {})
            | {
                "nemo_gym_agent": self.config.name,
                "instance_id": body.instance_id[:63],
            },
            resources=sandbox_resources,
            provider_options=self.config.sandbox_config.get("provider_options", {}),
        )
        sandbox = AsyncSandbox(provider_config)
        await sandbox.start(spec)
        await sandbox.exec(f"ln -sfn /workspace {shlex.quote(body.workdir)}")
        return sandbox

    async def _stop_sandbox(self, sandbox: AsyncSandbox | None) -> None:
        if sandbox is None:
            return
        try:
            await sandbox.stop()
        except Exception:
            print("Failed to stop SWE-Next sandbox", format_exc(), file=sys.stderr)

    async def _init_git_repo(self, sandbox: AsyncSandbox, workdir: str) -> None:
        """These images have no git history at all -- init one fresh so ``seed_session`` has a
        real base commit to diff the agent's changes against, and the anti-cheat scrub has an
        actual repo to act on.
        """
        result = await sandbox.exec(
            f"cd {shlex.quote(workdir)} && git init -q "
            f"&& git config user.email nemo-gym@nvidia.com && git config user.name nemo-gym "
            f"&& git add -A && git commit -q -m 'nemo_gym: initial snapshot' --allow-empty"
        )
        if result.return_code != 0:
            print(f"Failed to init git repo at {workdir}: {result.stdout}\n{result.stderr}", file=sys.stderr)

    async def _pristine_untracked_files(self, sandbox: AsyncSandbox, workdir: str) -> frozenset[str]:
        """List of files ``workdir`` holds untracked before the agent touches it."""
        try:
            result = await sandbox.exec(f"git -C {shlex.quote(workdir)} ls-files --others --exclude-standard")
            if result.return_code != 0:
                print(f"Failed to list pristine untracked files: {result.stderr}", file=sys.stderr)
                return frozenset()
            return frozenset(line.strip() for line in (result.stdout or "").splitlines() if line.strip())
        except Exception:
            print("Failed to list pristine untracked files", format_exc(), file=sys.stderr)
            return frozenset()

    async def _extract_model_patch(self, session_id: str, workdir: str, base_commit: str) -> str:
        """Diff the agent's own sandbox against ``base_commit``, then stop it.

        ``git add -N`` (intent-to-add) is what makes brand-new files show up in ``git diff`` too,
        not just edits to already-tracked files.
        """
        original_sandbox = self._session_id_to_sandbox.pop(session_id)
        pristine_untracked = self._session_id_to_pristine_untracked.pop(session_id, frozenset())
        try:
            result = await original_sandbox.exec(
                f"git -C {shlex.quote(workdir)} add -N . "
                f"&& git -C {shlex.quote(workdir)} --no-pager diff {shlex.quote(base_commit)}"
            )
            if result.return_code != 0:
                raise RuntimeError(result.stderr or "git diff failed")
            return drop_patch_sections(result.stdout or "", pristine_untracked)
        finally:
            await self._stop_sandbox(original_sandbox)

    async def seed_session(self, request: Request, body: SWENextSeedSessionRequest) -> SWENextSeedSessionResponse:
        """Start the instance's image so an agent can work in it."""
        session_id = request.session[SESSION_ID_KEY]
        await self._stop_sandbox(self._session_id_to_sandbox.pop(session_id, None))
        self._session_id_to_pristine_untracked.pop(session_id, None)
        self._session_id_to_base_commit.pop(session_id, None)

        sandbox = await self._create_sandbox(body)
        await hide_grading_artifacts(sandbox, body.workdir)
        await self._init_git_repo(sandbox, body.workdir)
        if self.config.apply_anti_cheating:
            await apply_anti_cheat_setup(sandbox, body.workdir, body.instance_id, "swe_next")

        head_result = await sandbox.exec(f"git -C {shlex.quote(body.workdir)} rev-parse HEAD")
        self._session_id_to_base_commit[session_id] = (head_result.stdout or "").strip()
        self._session_id_to_pristine_untracked[session_id] = await self._pristine_untracked_files(
            sandbox, body.workdir
        )
        self._session_id_to_sandbox[session_id] = sandbox
        return SWENextSeedSessionResponse(sandbox_handle=str(sandbox._handle.sandbox_id))

    async def verify(self, request: Request, body: SWENextVerifyRequest) -> SWENextVerifyResponse:
        session_id = request.session[SESSION_ID_KEY]
        extraction_error = None
        if self.config.is_verifying_golden_patch:
            patch = body.patch
        else:
            base_commit = self._session_id_to_base_commit.pop(session_id, "")
            if not base_commit:
                patch = ""
                extraction_error = "Failed to extract model patch: no base commit recorded (seed_session did not run for this session)"
            else:
                try:
                    patch = await self._extract_model_patch(session_id, body.workdir, base_commit)
                except Exception as exc:
                    patch = ""
                    extraction_error = f"Failed to extract model patch: {exc}"

        inputs = self._inputs(body, patch)
        log_dir = Path(__file__).parent / "logs" / body.instance_id

        files = verification_files(inputs)
        attempts = 1 + max(self.config.inconclusive_verification_retries, 0)
        start_time_taken = 0.0
        verification_time_taken = 0.0
        result = VerificationResult(
            completed=False,
            resolved=False,
            patch_applied=False,
            test_results=None,
            test_output="",
            error="unattempted",
        )
        for attempt in range(1, attempts + 1):
            sandbox: AsyncSandbox | None = None
            started = time()
            try:
                sandbox = await self._create_sandbox(body, files=files)
                start_time_taken = time() - started
                verification_started = time()
                result = await run_verification(
                    sandbox=sandbox,
                    inputs=inputs,
                    timeout_s=self.config.evaluation_timeout,
                    log_dir=log_dir,
                )
                verification_time_taken = time() - verification_started
            except Exception as exc:
                start_time_taken = time() - started
                verification_time_taken = 0.0
                result = VerificationResult(
                    completed=False,
                    resolved=False,
                    patch_applied=False,
                    test_results=None,
                    test_output="",
                    error=f"Verification failed: {exc}",
                )
            finally:
                await self._stop_sandbox(sandbox)
            if result.completed:
                break
            if attempt < attempts:
                print(
                    f"[swe_next] {body.instance_id}: inconclusive ({result.error}); "
                    f"retrying on a fresh sandbox ({attempt}/{attempts - 1})",
                    flush=True,
                )

        return SWENextVerifyResponse.model_validate(
            body.model_dump()
            | {
                # An unresolved-but-completed run is a real 0. An incomplete run is also 0, but
                # evaluation_completed distinguishes them so a broken row is not read as a hard task.
                "reward": 1.0 if result.resolved else 0.0,
                "evaluation_completed": result.completed,
                "resolved": result.resolved,
                "patch_applied": result.patch_applied,
                "instance_id": body.instance_id,
                "language": body.language,
                "test_results": result.test_results,
                "test_output": result.test_output[-100_000:],
                "error": extraction_error or result.error,
                "eval_sandbox_start_time_taken": start_time_taken,
                "patch_verification_time_taken": verification_time_taken,
            }
        )


if __name__ == "__main__":
    SWENextResourcesServer.run_webserver()
elif is_nemo_gym_fastapi_entrypoint(__file__):
    # Required whenever num_workers > 1. Multi-worker uvicorn re-imports this entrypoint BY PATH
    # in each forked child and expects a module-level `app`; without it every child exits, and
    # uvicorn responds by stopping the parent. The server then never binds, so the symptom is not
    # an import error but a flood of connection failures from clients talking to a dead port.
    app = SWENextResourcesServer.run_webserver()  # noqa: F401
