# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Run one TIGER-Lab/SWE-Next task's tests in a sandbox and grade the result.

SWE-Next is generated by the R2E ("Repo-to-Environment") pipeline: every row's image bakes an
isolated venv at ``/env/.venv`` (symlinked to ``/testbed/.venv``, since ``ln -s /workspace
/testbed`` and an earlier ``ln -s /env/.venv /workspace/.venv``), a fixed ``run_tests.sh`` recipe,
and a canonical injected test file under ``r2e_tests/``. Confirmed verbatim identical across a
200-row sample of the raw Hub data, so this server hardcodes it rather than reading it per row:

    PYTEST_DISABLE_PLUGIN_AUTOLOAD=1 PYTHONWARNINGS='ignore::UserWarning,ignore::SyntaxWarning' \\
        .venv/bin/python -W ignore -m pytest -rA r2e_tests

Grading mirrors the upstream reference implementation exactly (TIGER-AI-Lab/SWE-Next's own
``DockerRuntime._calculate_reward_r2e``, the reward path R2E-edit rows use by default), NOT the
SWE-bench FAIL_TO_PASS/PASS_TO_PASS convention this dataset's own fields would suggest:

  - Every row also carries ``expected_output_json``, a ``{test_name: "PASSED"|"FAILED"|"ERROR"}``
    snapshot of the ENTIRE test suite captured on the golden-patched instance -- a strict superset
    of FAIL_TO_PASS/PASS_TO_PASS (verified: every FAIL_TO_PASS/PASS_TO_PASS id is present in it).
  - The reference reward is lenient, not a targeted FAIL_TO_PASS/PASS_TO_PASS check: for every test
    ``expected_output_json`` marked PASSED, the fresh run must ALSO observe it PASSED. Anything
    expected FAILED/ERROR is unconstrained -- an agent is allowed to fix more than the golden patch
    did. ``resolved = no expected-PASSED test is missing or came back non-PASSED``.
  - Both ``expected_output_json`` and the fresh run are parsed by the IDENTICAL function
    (upstream's ``parse_log_pytest``, reimplemented here as ``parse_pytest_short_summary``): read
    the "short test summary info" section pytest's ``-rA`` flag prints, and for each ``STATUS
    path::Class::method`` line, drop only the file-path segment (split on the FIRST "::") and keep
    the rest verbatim (including any further "::" inside a parametrize bracket, and the bracket
    itself). Since both sides come from the same parser, matching is a plain exact-key lookup --
    no suffix heuristics needed, and none of the ambiguity a JUnit-XML-based parse would introduce
    (JUnit's ``classname`` is a DOTTED module path, not this dataset's own bare/``Class::method``
    convention, and reconstructing the boundary is inherently lossy for repos with same-named
    classes in different modules).
"""

from __future__ import annotations

import json
import re
import shlex
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterable


TEST_OUTPUT_BEGIN = "___NEMO_GYM_SWE_NEXT_TEST_BEGIN___"
TEST_OUTPUT_END = "___NEMO_GYM_SWE_NEXT_TEST_END___"

# Confirmed byte-identical across a 200-row sample of the raw Hub data (see module docstring).
# `-rA` is what prints the "short test summary info" section `parse_pytest_short_summary` reads.
TEST_COMMAND = (
    "PYTEST_DISABLE_PLUGIN_AUTOLOAD=1 "
    "PYTHONWARNINGS='ignore::UserWarning,ignore::SyntaxWarning' "
    ".venv/bin/python -W ignore -m pytest -rA r2e_tests"
)

PASSED = "PASSED"
_ANSI_ESCAPE_RE = re.compile(r"\x1b\[[0-9;]*m")


def _strip_ansi(text: str) -> str:
    return _ANSI_ESCAPE_RE.sub("", text)


@dataclass
class VerificationInputs:
    instance_id: str
    workdir: str
    patch: str
    test_patch: str
    expected_output_json: str = "{}"


@dataclass
class VerificationResult:
    completed: bool
    resolved: bool
    patch_applied: bool
    test_results: dict[str, Any] | None
    test_output: str
    error: str | None = None


def patch_section_path(section: str) -> str | None:
    """Return the repository-relative path one ``diff --git`` section targets."""
    a_path: str | None = None
    b_path: str | None = None
    for line in section.splitlines():
        if line.startswith("@@"):
            break
        if line.startswith("--- ") and a_path is None:
            value = line[4:].strip()
            a_path = None if value == "/dev/null" else value.removeprefix("a/")
        elif line.startswith("+++ ") and b_path is None:
            value = line[4:].strip()
            b_path = None if value == "/dev/null" else value.removeprefix("b/")

    if b_path or a_path:
        return b_path or a_path

    header = re.match(r"^diff --git a/(.+?) b/(.+)$", section.splitlines()[0] if section else "")
    return header.group(2) if header else None


def drop_patch_sections(patch: str, paths: Iterable[str]) -> str:
    """Drop the diff sections targeting ``paths``.

    ``git add -N . && git diff`` picks up every untracked file, including ones that were already
    untracked before the agent touched anything. Excluding those paths keeps the extracted patch
    to what the agent actually changed.
    """
    dropped = set(paths)
    if not patch or not dropped:
        return patch

    kept: list[str] = []
    for section in re.split(r"(?=^diff --git )", patch, flags=re.MULTILINE):
        if not section.strip():
            continue
        path = patch_section_path(section)
        if path is not None and path in dropped:
            continue
        kept.append(section)

    return "".join(kept)


def build_eval_script(inputs: VerificationInputs) -> str:
    apply_patch = (
        "git apply --reject --recount --ignore-space-change --whitespace=nowarn /tmp/nemo_gym_patch.diff || true"
        if inputs.patch.strip()
        else ""
    )
    apply_test_patch = (
        "git apply --reject --recount --ignore-space-change --whitespace=nowarn /tmp/nemo_gym_test_patch.diff || true"
        if inputs.test_patch.strip()
        else ""
    )

    return f"""#!/bin/bash
cd {shlex.quote(inputs.workdir)} || exit 97
set +e
{apply_patch}
{apply_test_patch}

echo "{TEST_OUTPUT_BEGIN}"
{TEST_COMMAND}
__test_exit=$?
echo "{TEST_OUTPUT_END}"
exit $__test_exit
"""


def _slice(log: str, begin: str, end: str) -> str:
    start = log.find(begin)
    if start == -1:
        return ""
    start += len(begin)
    stop = log.find(end, start)
    return log[start:stop] if stop != -1 else log[start:]


def verification_files(inputs: VerificationInputs) -> dict[str, str]:
    files = {"/tmp/nemo_gym_eval.sh": build_eval_script(inputs)}
    if inputs.patch.strip():
        files["/tmp/nemo_gym_patch.diff"] = inputs.patch
    if inputs.test_patch.strip():
        files["/tmp/nemo_gym_test_patch.diff"] = inputs.test_patch
    return files


def parse_pytest_short_summary(output: str) -> dict[str, str]:
    """Reimplementation of upstream's ``execution_log_parser.parse_log_pytest``.

    Prefers the "short test summary info" block (compact, stable across pytest versions);
    falls back to scanning the whole log for ``STATUS path::name`` lines otherwise. A test's key
    is everything after the FIRST "::" (dropping only the file-path segment) with any trailing
    " - message" stripped -- deliberately NOT a full class/method split, since a parametrize
    bracket can itself contain "::" as data (e.g. an f-string format spec) and this dataset's own
    ``expected_output_json`` was captured by this exact same rule, so matching only needs the two
    sides to agree with each other, not to be "correct" pytest-id parsing in the abstract.
    """
    cleaned = _ANSI_ESCAPE_RE.sub("", output).replace("\r", "")
    if "short test summary info" in cleaned:
        lines = cleaned.split("short test summary info", 1)[1].strip().split("\n")
    else:
        lines = cleaned.splitlines()

    statuses: dict[str, str] = {}
    for line in lines:
        stripped = line.strip()
        if not stripped:
            continue

        status: str | None = None
        if "PASSED" in stripped:
            status = "PASSED"
        elif "FAILED" in stripped:
            status = "FAILED"
        elif "ERROR" in stripped:
            status = "ERROR"
        if status is None:
            continue

        if "::" in stripped:
            test_name = stripped.split("::", 1)[1].split(" - ")[0]
        else:
            parts = stripped.split()
            try:
                idx = parts.index(status)
            except ValueError:
                idx = 0
            test_name = " ".join(parts[idx + 1 :]).split(" - ")[0] if len(parts) > idx + 1 else stripped

        statuses[test_name] = status
    return statuses


def grade(expected: dict[str, str], parsed: dict[str, str]) -> dict[str, Any]:
    """Upstream's ``_calculate_reward_r2e`` semantics: every expected-PASSED test must still be
    observed PASSED; expected-FAILED/ERROR tests are unconstrained (an agent may fix more than the
    golden patch did). ``expected`` and ``parsed`` come from the identical parser (see module
    docstring), so this is a plain exact-key lookup -- no suffix matching. A handful of raw rows
    (e.g. elastic/rally) bake ANSI color codes into ``expected_output_json``'s own keys, not just
    FAIL_TO_PASS/PASS_TO_PASS -- stripped here too, on both sides, so those rows are gradeable."""
    expected = {_strip_ansi(k): v for k, v in expected.items()}
    parsed = {_strip_ansi(k): v for k, v in parsed.items()}
    missing: list[str] = []
    mismatched: list[str] = []
    required_pass_total = 0
    for name, exp_status in expected.items():
        if exp_status != PASSED:
            continue
        required_pass_total += 1
        got = parsed.get(name)
        if got is None:
            missing.append(name)
        elif got != PASSED:
            mismatched.append(name)

    return {
        "expected_total": len(expected),
        "parsed_total": len(parsed),
        "required_pass_total": required_pass_total,
        "missing": missing[:20],
        "missing_total": len(missing),
        "mismatched": mismatched[:20],
        "mismatched_total": len(mismatched),
        "resolved": not missing and not mismatched,
    }


async def run_verification(
    sandbox: Any,
    inputs: VerificationInputs,
    timeout_s: float | None = None,
    log_dir: Path | None = None,
) -> VerificationResult:
    import asyncio

    result = await sandbox.exec("bash /tmp/nemo_gym_eval.sh", timeout_s=timeout_s)
    output = (result.stdout or "") + (("\n" + result.stderr) if result.stderr else "")

    if log_dir is not None:

        def _persist() -> None:
            try:
                log_dir.mkdir(parents=True, exist_ok=True)
                (log_dir / "test_output.log").write_text(output, errors="replace")
            except OSError:
                pass

        await asyncio.to_thread(_persist)

    if result.return_code == 97:
        return VerificationResult(
            completed=False,
            resolved=False,
            patch_applied=False,
            test_results=None,
            test_output=output,
            error=f"workdir {inputs.workdir} not present in the image",
        )

    stdout_section = _slice(output, TEST_OUTPUT_BEGIN, TEST_OUTPUT_END)

    try:
        expected = json.loads(inputs.expected_output_json or "{}")
    except Exception as exc:
        return VerificationResult(
            completed=False,
            resolved=False,
            patch_applied=True,
            test_results=None,
            test_output=output,
            error=f"invalid expected_output_json: {exc}",
        )
    if not expected:
        return VerificationResult(
            completed=False,
            resolved=False,
            patch_applied=True,
            test_results=None,
            test_output=output,
            error="empty expected_output_json: row cannot be graded",
        )

    try:
        parsed = await asyncio.to_thread(parse_pytest_short_summary, stdout_section)
    except Exception as exc:
        return VerificationResult(
            completed=False,
            resolved=False,
            patch_applied=True,
            test_results=None,
            test_output=output,
            error=f"parse failure (pytest): {exc}",
        )

    report = grade(expected, parsed)
    return VerificationResult(
        completed=True,
        resolved=bool(report["resolved"]),
        patch_applied=True,
        test_results=report,
        test_output=output,
    )
