config_paths:
- resources_servers/evalplus/configs/evalplus.yaml

mbpp_evalplus_resources_server:
  _inherit_from: evalplus
  resources_servers:
    evalplus:
      dataset: mbpp

      datasets:
      - name: mbpp
        type: benchmark
        jsonl_fpath: benchmarks/mbpp/data/mbpp_benchmark.jsonl
        prompt_config: benchmarks/mbpp/prompts/default.yaml
        prepare_script: benchmarks/mbpp/prepare.py
        license: MIT
        agent: mbpp_evalplus_simple_agent
mbpp_evalplus_simple_agent:
  _inherit_from: evalplus_simple_agent
  responses_api_agents:
    simple_agent:
      resources_server:
        name: mbpp_evalplus_resources_server
