harbor_agent_general:
  responses_api_agents:
    harbor_agent_general:
      entrypoint: app.py
      domain: agent
      description: Harbor integration for agent harnesses with Singularity environments.

      ## NOTE: Optional fallback to co-locate jobs directory with the output_jsonl_fpath.
      harbor_jobs_dir: ${oc.select:harbor_jobs_dir,${output_jsonl_fpath}}

      ##
      # Follows harbor.models.job.config:DatasetConfig spec.
      #
      harbor_dataset:
        path: ${harbor_dataset_path}

      ##
      # Follows harbor.models.trial.config:EnvironmentConfig spec.
      #
      harbor_environment:
        type: singularity
        kwargs:
          singularity_image_cache_dir: ${oc.env:SINGULARITY_CACHEDIR}/harbor
          singularity_force_pull: ${oc.env:SINGULARITY_FORCE_PULL,false}
          ## CAUTION: DO NOT use bind-paths, to avoid broken network access.
          singularity_no_mount: home,tmp

      ##
      # Follows harbor.models.trial.config:AgentConfig spec.
      #
      harbor_agent:
        name: opencode
        ## TIP: Directly use Gym's native expected variable name.
        model_name: ${policy_model_name}
        ##
        # TIP: Escape $ so that secret variables are not exposed in the written Harbor configuration, and resolved directly within Harbor.
        # If the variables are unlikely to change and exposure is not a concern, use immediate resolution via Hydra. e.g. ${oc.env:NVINF_API_KEY}
        #
        # env:
          # NVINF_API_KEY: \${NVINF_API_KEY}
          # VLLM_API_BASE: \${VLLM_API_BASE}

      ##
      # Follows harbor.models.trial.config:VerifierConfig spec.
      #
      # harbor_verifier:
      #   disable: false
