bbh_aviary_resources_server:
  resources_servers:
    aviary:
      entrypoint: hypotest_app.py
      domain: coding
      dataset:
        problem_jsonl: data/bbh.jsonl
        capsule_dir: /capsules
        work_dir: /workspace
        force_python: true
        rubric_model:
        - insert rubric model
        rubric_model_config:
          reasoning_effort: medium
          model_list:
          - model_name:
            - insert model name
            litellm_params:
              model:
              - insert model api name
              api_key:
              - insert model api key
              base_url:
              - insert model api url
        use_docker: false
        use_enroot: true
        container_sqsh_path:
        - insert path to container if using enroot containerization
        execution_config:
          cell_execution_timeout: 180
          job_timeout: 1800
      verified: false
      datasets:
      - name: example
        type: example
        jsonl_fpath: environments/aviary_bbh/data/example.jsonl
bbh_aviary_agent:
  responses_api_agents:
    aviary_agent:
      entrypoint: app.py
      max_steps: 100
      return_transitions: false
      resources_server:
        type: resources_servers
        name: bbh_aviary_resources_server
      model_server:
        type: responses_api_models
        name: policy_model
      max_total_sequence_length: 80000
