# Chain to existing resource server + agent config
config_paths:
- resources_servers/mcqa/configs/mcqa.yaml

# We use `_inherit_from` directives to inherit from and not use the generic config above to ensure this benchmark config is isolated.
gpqa_mcqa_resources_server:
  _inherit_from: mcqa
  resources_servers:
    mcqa:
      # Override mcqa server grading mode to match the prompt format (Answer: X)
      grading_mode: lenient_answer_colon_md

      datasets:
      - name: gpqa
        type: benchmark
        jsonl_fpath: benchmarks/gpqa/data/gpqa_diamond_benchmark.jsonl
        prompt_config: benchmarks/prompts/eval/aai/mcq-4choices.yaml
        prepare_script: benchmarks/gpqa/prepare.py
        num_repeats: 8
        agent: gpqa_mcqa_simple_agent
gpqa_mcqa_simple_agent:
  _inherit_from: mcqa_simple_agent
  responses_api_agents:
    simple_agent:
      resources_server:
        name: gpqa_mcqa_resources_server
