config_paths:
  - responses_api_agents/aviary_agent/configs/aviary_agent.yaml

# NOTE: AviaryResourcesServer is an abstract base server and cannot be instantiated directly,
# so here we run the GSM8k server for tests/examples. Users should use the other configurations
# in this directory to instantiate their desired server.
gsm8k_aviary_resources_server:
  resources_servers:
    aviary:
      entrypoint: gsm8k_app.py
      domain: math
      verified: false
gsm8k_aviary_agent:
  _inherit_from: aviary_agent
  responses_api_agents:
    aviary_agent:
      resources_server:
        type: resources_servers
        name: gsm8k_aviary_resources_server
