# grading_rule options: seq_match, weighted_seq_match, exact (default)
lc_equivalence_rule:
  resources_servers:
    equivalence_rule:
      entrypoint: app.py
      grading_rule: exact
      domain: knowledge
      verified: false
      description: Question - Answering with rule-based reward
      value: Improve retrieval and counting capabilities

      datasets:
      - name: example
        type: example
        jsonl_fpath: resources_servers/equivalence_rule/data/example.jsonl
lc_equivalence_rule_simple_agent:
  responses_api_agents:
    simple_agent:
      entrypoint: app.py
      resources_server:
        type: resources_servers
        name: lc_equivalence_rule
      model_server:
        type: responses_api_models
        name: policy_model
