instruction_following:
  resources_servers:
    instruction_following:
      entrypoint: app.py
      domain: instruction_following
      verified: false
      description: Instruction following datasets targeting IFEval and IFBench style instruction following capabilities
      value: Improve IFEval and IFBench

      datasets:
      - name: example
        type: example
        jsonl_fpath: environments/instruction_following/data/example.jsonl
      - name: train
        type: train
        jsonl_fpath: environments/instruction_following/data/train.jsonl
        huggingface_identifier:
          repo_id: nvidia/Nemotron-RL-instruction_following
          artifact_fpath: instruction_following.jsonl
        license: Apache 2.0
instruction_following_simple_agent:
  responses_api_agents:
    simple_agent:
      entrypoint: app.py
      resources_server:
        type: resources_servers
        name: instruction_following
      model_server:
        type: responses_api_models
        name: policy_model
