reasoning_gym:
  resources_servers:
    reasoning_gym:
      entrypoint: app.py
      domain: knowledge
      verified: false
      description: Over 100 tasks including algebra, arithmetic, computation, cognition, geometry, graph theory, logic, and many common games.
      value: Improve robustness, generalization, broad knowledge and reasoning

      datasets:
      - name: example
        type: example
        jsonl_fpath: environments/reasoning_gym/data/example.jsonl
      - name: train
        type: train
        jsonl_fpath: environments/reasoning_gym/data/train.jsonl
        huggingface_identifier:
          repo_id: nvidia/Nemotron-RL-ReasoningGym-v1
          artifact_fpath: data/train.jsonl
        license: Creative Commons Attribution 4.0 International
reasoning_gym_simple_agent:
  responses_api_agents:
    simple_agent:
      entrypoint: app.py
      resources_server:
        type: resources_servers
        name: reasoning_gym
      model_server:
        type: responses_api_models
        name: policy_model
