aalcr_resources_server:
  resources_servers:
    aalcr:
      entrypoint: app.py
      domain: other
      verified: false
      judge_model_server:
        type: responses_api_models
        name: Qwen3-235B-A22B-Instruct-2507-FP8
      judge_responses_create_params_overrides: {}
      datasets:
      - name: example
        type: example
        jsonl_fpath: resources_servers/aalcr/data/example.jsonl
        num_repeats: 1
aalcr_simple_agent:
  responses_api_agents:
    simple_agent:
      entrypoint: app.py
      resources_server:
        type: resources_servers
        name: aalcr_resources_server
      model_server:
        type: responses_api_models
        name: policy_model
