# Chain to existing resource server + agent config
config_paths:
- resources_servers/spider2_lite/configs/spider2_lite.yaml

# We use `_inherit_from` directives to inherit from and not use the generic config above to ensure this benchmark config is isolated.
spider2_lite_benchmark_resources_server:
  _inherit_from: spider2_lite_resources_server

  resources_servers:
    spider2_lite:
      datasets:
      - name: spider2_lite
        type: benchmark
        jsonl_fpath: benchmarks/spider2_lite/data/spider2_lite_benchmark.jsonl
        prompt_config:
        prepare_script: benchmarks/spider2_lite/prepare.py
        num_repeats: 16
        agent: spider2_lite_benchmark_simple_agent
spider2_lite_benchmark_simple_agent:
  _inherit_from: spider2_lite_simple_agent
  responses_api_agents:
    simple_agent:
      resources_server:
        name: spider2_lite_benchmark_resources_server
