# Chain to existing resource server + agent config
config_paths:
- resources_servers/xstest/configs/xstest.yaml

# We use `_inherit_from` directives to inherit from and not use the generic config above to ensure this benchmark config is isolated.
xstest_benchmark_resources_server:
  _inherit_from: xstest_resources_server

  resources_servers:
    xstest:
      datasets:
      - name: xstest
        type: benchmark
        jsonl_fpath: benchmarks/xstest/data/xstest_benchmark.jsonl
        prompt_config:
        prepare_script: benchmarks/xstest/prepare.py
        num_repeats: 4
        agent: xstest_benchmark_simple_agent
xstest_benchmark_simple_agent:
  _inherit_from: xstest_simple_agent
  responses_api_agents:
    simple_agent:
      resources_server:
        name: xstest_benchmark_resources_server
