# SWE-bench wrapper configuration for OpenHands
swe_agents_train:
  responses_api_agents:
    swe_agents:
      entrypoint: app.py
      # Agent framework configuration
      agent_framework: openhands
      agent_config: responses_api_agents/swe_agents/configs/oh_config.toml
      agent_max_turns: 100
      agent_framework_repo: https://github.com/sdevare-nv/nv-OpenHands.git
      agent_framework_commit: 54d2a95edc666551b854a7e5d4205ec69e60ff23  # pragma: allowlist secret
      # Container configuration
      container_formatter: ???
      container_folder_path: null
      swebench_agent_timeout: 1800
      swebench_tests_timeout: 1200
      apptainer_memory_limit_mb: 32768
      command_exec_timeout: 300
      dataset_path: ???
      agent_prompt_overrides:
      # # Codex agent
      # - user_prompt_template: responses_api_agents/swe_agents/prompts/codex/user_prompt.j2
      #   system_prompt_template: responses_api_agents/swe_agents/prompts/codex/system_prompt.j2
      #   agent_cls: CodexAgent
      #   diversify_tool_names: false

      # # OpenCode agent
      # - user_prompt_template: responses_api_agents/swe_agents/prompts/opencode/user_prompt.j2
      #   system_prompt_template: responses_api_agents/swe_agents/prompts/opencode/system_prompt.j2
      #   agent_cls: OpenCodeAgent
      #   diversify_tool_names: false
      
      # CodeAct agent
      - user_prompt_template: responses_api_agents/swe_agents/prompts/openhands/user_prompt.j2
        system_prompt_template: responses_api_agents/swe_agents/prompts/openhands/system_prompt.j2
        agent_cls: CodeActAgent
        diversify_tool_names: false
      
      model_server:
        name: policy_model # openai_model
        type: responses_api_models
      datasets:
        - name: train
          type: train
          jsonl_fpath: responses_api_agents/swe_agents/data/swegym_for_sweagent_and_openhands.jsonl
          gitlab_identifier:
            dataset_name: swegym_for_sweagent_and_openhands
            version: 0.0.2
            artifact_fpath: swegym-converted.jsonl
          license: Apache 2.0
        - name: example
          type: example
          jsonl_fpath: responses_api_agents/swe_agents/data/example.jsonl
swe_agents_val:
  responses_api_agents:
    swe_agents:
      entrypoint: app.py
      # Agent framework configuration
      agent_framework: openhands
      agent_config: responses_api_agents/swe_agents/configs/oh_config.toml
      agent_max_turns: 100
      agent_framework_repo: https://github.com/sdevare-nv/nv-OpenHands.git
      agent_framework_commit: 54d2a95edc666551b854a7e5d4205ec69e60ff23  # pragma: allowlist secret
      # Container configuration
      container_formatter: ???
      container_folder_path: null
      swebench_agent_timeout: 1800
      swebench_tests_timeout: 1200
      apptainer_memory_limit_mb: 32768
      command_exec_timeout: 300
      dataset_path: ???
      
      agent_prompt_overrides:
      
      # CodeAct agent
      - user_prompt_template: responses_api_agents/swe_agents/prompts/openhands/user_prompt.j2
        system_prompt_template: responses_api_agents/swe_agents/prompts/openhands/system_prompt.j2
        agent_cls: CodeActAgent
        diversify_tool_names: false
      
      # Optional model server reference
      model_server:
        name: policy_model # openai_model
        type: responses_api_models
      datasets:
        - name: validation
          type: validation
          jsonl_fpath: responses_api_agents/swe_agents/data/swebench_verified_for_sweagent_and_openhands.jsonl
          gitlab_identifier:
            dataset_name: swebench_verified_for_sweagent_and_openhands
            version: 0.0.1
            artifact_fpath: swebench_verified_for_sweagent_and_openhands.jsonl
          license: TBD

swe_agents_train_environment_server:
  environment_servers:
    legacy_agent:
      entrypoint: app.py
      agent_server:
        type: responses_api_agents
        name: swe_agents_train

swe_agents_val_environment_server:
  environment_servers:
    legacy_agent:
      entrypoint: app.py
      agent_server:
        type: responses_api_agents
        name: swe_agents_val
