config_paths:
- resources_servers/ruler/configs/ruler.yaml
- responses_api_models/local_vllm_model/configs/pretrain_text_completion.yaml

ruler_pretrain_resources_server:
  _inherit_from: ruler_resources_server

  resources_servers:
    ruler:
      datasets:
      - name: ruler_pretrain
        type: benchmark
        jsonl_fpath: benchmarks/ruler/data/ruler_pretrain.jsonl
        prompt_config:
        prepare_script: benchmarks/ruler/prepare_utils.py
        num_repeats: 1
        agent: ruler_pretrain_simple_agent
ruler_pretrain_simple_agent:
  _inherit_from: ruler_simple_agent
  responses_api_agents:
    simple_agent:
      resources_server:
        name: ruler_pretrain_resources_server
      model_server:
        name: policy_model
