calendar:
  resources_servers:
    calendar:
      entrypoint: app.py
      domain: agent
      verified: false
      description: Multi-turn calendar scheduling dataset. User states events and constraints in natural language; model schedules events to satisfy all constraints.
      value: Improve multi-turn instruction following capabilities
      datasets:
      - name: train
        type: train
        jsonl_fpath: environments/calendar/data/train.jsonl
        huggingface_identifier:
          repo_id: nvidia/Nemotron-RL-agent-calendar_scheduling
          artifact_fpath: train.jsonl
        license: Apache 2.0
      - name: validation
        type: validation
        jsonl_fpath: environments/calendar/data/validation.jsonl
        huggingface_identifier:
          repo_id: nvidia/Nemotron-RL-agent-calendar_scheduling
          artifact_fpath: validation.jsonl
        license: Apache 2.0
      - name: example
        type: example
        jsonl_fpath: environments/calendar/data/example.jsonl
calendar_simple_agent:
  responses_api_agents:
    simple_agent:
      entrypoint: app.py
      resources_server:
        type: resources_servers
        name: calendar
      model_server:
        type: responses_api_models
        name: policy_model
