# Chain to existing resource server + agent config
config_paths:
- resources_servers/code_gen/configs/code_gen.yaml

# We use `_inherit_from` directives to inherit from and not use the generic config above to ensure this benchmark config is isolated.
livecodebench_v6_code_gen_resources_server:
  _inherit_from: code_gen

  resources_servers:
    code_gen:
      datasets:
      - name: livecodebench_v6
        type: benchmark
        jsonl_fpath: benchmarks/livecodebench/v6_2408_2505/data/livecodebench_v6_validation.jsonl
        prompt_config: benchmarks/prompts/eval/livecodebench/default_reasoning.yaml
        prepare_script: benchmarks/livecodebench/v6_2408_2505/prepare.py
        num_repeats: 3
        agent: livecodebench_v6_code_gen_simple_agent
livecodebench_v6_code_gen_simple_agent:
  _inherit_from: code_gen_simple_agent
  responses_api_agents:
    simple_agent:
      resources_server:
        name: livecodebench_v6_code_gen_resources_server
